### ISSUE TITLE
Worked perfect first few times, got strange crash error, can't load again

### ISSUE THREAD

**Issue by Avrution** [fqlx/XboxKeyboardMouse#145]
Didn't think much of the crash, so I just ignored it for the moment and then close the program.  

Next time I went to load, it goes through Launching Application and then it closes right down.  Removed/reinstalled the program and runtimes, but same thing.  

A new windows error report and local crash dump is created each time I try and run, but of course it gives no details to me.

**Comment by Avrution** [comment]
Won't let me edit my post, but I also see this in the event viewer each time it crashes

Application: XboxKeyboardMouse.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.Windows.Input.Key, WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[SimWinInput.GamePadControl, SimWinGamePad, Version=1.0.5.0, Culture=neutral, PublicKeyToken=null]].Insert(System.Windows.Input.Key, SimWinInput.GamePadControl, Boolean)
   at XboxKeyboardMouse.Program.ReloadControlScheme()
   at XboxKeyboardMouse.Program.ReloadActiveConfig()
   at XboxKeyboardMouse.Program.Main(System.String[])
